config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'themes#index'

  resources :themes, only: [:index, :show] do
    get 'posts', on: :collection
  end
end

app/models/abstract_collection.rb
class AbstractCollection
  include Enumerable

  attr_accessor :members

  def initialize(args = [])
    @members = []
    return unless args && args.any?
    args.each do |options|
      klass = self.class.name.gsub(/Collection\z/, "")
      @members << klass.constantize.new(options)
    end
  end

  def size
    members.size
  end

  def empty?
    members.empty?
  end

  def each
    members.each do |member|
      yield(member)
    end
  end

  def [](key)
    members[key]
  end

  def find(arg = nil)
    members.select { |m| m.id == arg }.first
  end

  def where(args = {})
    unless args.respond_to? :keys
      raise ArgumentError, "You must provide a hash with valid keys"
    end

    id = args[:id].to_i

    resources = members.select { |m| m.id == id }
    collection = self.class.new
    collection.members = resources
    collection
  end

  def attributes
    members.map(&:attributes)
  end

  def inspect
    attributes
  end

  def to_s
    attributes
  end
end

app/models/abstract_resource.rb
class AbstractResource
  def self.attribute(name)
    fields << name
    attr_accessor name
  end

  def self.attributes(*names)
    names.each do |name|
      attribute name
    end
  end

  def self.fields
    @fields = @fields.sort if @fields
    @fields ||= []
  end

  def initialize(args = {})
    args.each_pair do |attr, value|
      next if skip?(attr)

      if %w(id).include? attr
        send "#{attr}=", value.to_i
      else
        send "#{attr}=", value
      end
    end
  end

  def attributes
    Hash[self.class.fields.map { |f| [f, send(f)] }]
  end

  def inspect
    attributes
  end

  def to_s
    attributes
  end

  def each_pair
    attributes.each do |key, val|
      yield(key, val)
    end
  end

  def [](key)
    attributes[key]
  end

  protected

  def skip?(attr)
    !allowed_attribute?(attr)
  end

  def allowed_attribute?(attr)
    self.class.fields.include?(attr.to_sym)
  end

  class << self
    protected

    def collection
      "#{name}Collection".constantize
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < AbstractResource
  attributes :has_next_page, :cached, :next_page, :data, :posts

  def initialize(args = {})
    super(args)
    @posts = PostCollection.new args[:data] || data
  end

  def has_next_page?
    has_next_page
  end

  def next_page_params
    return nil unless has_next_page?
    Rack::Utils.parse_nested_query(URI.parse(next_page).query).except('api_token')
  end
end

app/models/post.rb
class Post < AbstractResource
  attributes :url, :source, :embed, :author, :image, :title, :original_timestamp,
             :next_page, :description, :created, :user_id, :visible, :comments, :social_feed_id,
             :social_post_id, :social_id, :phash, :height, :width, :original_image, :timestamp,
             :post_id, :user_rights, :nsfw_score, :language, :likes_count, :shares_count,
             :replies_count, :cta, :highlight, :pinned, :recur_frequency, :recur_offset, :geo,
             :tags, :popup_function, :tweet_urls, :retweeted_by, :custom_field, :offset,
             :ref_timestamp, :unique_offset, :relative_offset

  def initialize(args = {})
    super(args)
  end
end

app/models/post_collection.rb
class PostCollection < AbstractCollection
end

app/models/theme.rb
class Theme < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: :show

  def index
    @themes = Theme.all
  end

  def show
  end

  def posts
    @next_page_params = params[:next_page_params].present? ? params[:next_page_params] : {}

    @service = Services::TService.new(ENV['T_API_URL'])
    @feed = @service.feed(ENV['T_API_FEED_NAME'], @next_page_params.merge(api_token: ENV['T_API_TOKEN']) )

    payload = {
      posts: @feed.posts,
      next_page_params: @feed.next_page_params,
      has_next_page: @feed.has_next_page?
    }

    respond_to do |format|
      format.json { render json: payload }
    end
  end

  private

  def set_theme
    @theme = Theme.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UxExperiments</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= yield :head %>
  </head>

  <body class="<%= controller_name %>-<%= action_name %>">
    <%= yield %>
  </body>
</html>

app/views/themes/_index_nav.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<% end %>

<nav class="navbar navbar-toggleable-md navbar-light bg-faded sticky-top">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">UX Experiments</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <% @themes.each do |theme| %>
        <li class="nav-item">
          <%= link_to theme.name, theme_path(theme.id), class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/themes/index.html.erb
<%= render partial: 'index_nav' %>

<div class="container themes-index-container">
  <div class="theme-selector">
    <div class="header">
      Select a theme
    </div>
    <ul class="content">
      <% @themes.each do |theme| %>
        <li>
          <%= link_to theme.name, theme_path(theme.id), class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/themes/show.html.erb
<% content_for :head do %>
  <%= javascript_include_tag @theme.js_file_name, 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag @theme.js_file_name, media: 'all', 'data-turbolinks-track' => true %>
<% end %>

<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
  <div class="box col4 template">
    <div class="img-container">
    </div>
    <div class="content-container">
      <p class="title">
      </p>
      <p class="username">
      </p>
    </div>
  </div>
</div>